POST http://localhost:5000/bot/hook
Content-Type: application/json

{
    "channel_id": "hawos4dqtby53pd64o4a4cmeoo",
    "channel_name": "town-square",
    "team_domain": "someteam",
    "team_id": "kwoknj9nwpypzgzy78wkw516qe",
    "post_id": "axdygg1957njfe5pu38saikdho",
    "text": "some+text+here",
    "timestamp": "1445532266",
    "token": "zmigewsanbbsdf59xnmduzypjc",
    "trigger_word": "some",
    "user_id": "rnina9994bde8mua79zqcg5hmo",
    "user_name": "somename",
    "file_ids": "znana9194bde8mua70zqcg5hmo"
}